### PR TITLE
Socket.io

### PR DESCRIPTION
**Pull request by Hy0tic**
Changes:
- add socket.io implementation in server and socket.io client in client side
- implemented room chat
- created UI for `/room` page, it takes in query parameter username and roomname (e.g `/room?username=Hyotic&room=castle`)
- add prettier

Questions:
- should types have their own files?
- should we use tailwindcss in all places instead of just css?

Todo:
- ~validate that users can't have the same name in the same room~
- ~add host room button~
- ~validate that room name is not taken when hosting room~
- ~autofocus username field on `/` page~
- ~validate username length and room name length~
- ~validate that user message is not null before sending~
- ~autofocus chat entry area so user can just start typing~
- ~~auto scroll to the newest chat message~~
- list of users should be virtual scroller (UI component from primevue) (or should it?)
- add copy room name or copy url (?) button

Libs added:
- primevue (UI components)
- socket.io and socket.io client
- moment (handle parsing date)
- prettier and tailwind prettier plugin

room page:
image

### CODE REVIEW

**Comment by Froidland** [comment]
please use prettier ;-;

**Comment by Hy0tic** [comment]
> please use prettier ;-;

done, u might hate my prettier config tho

**Comment by Froidland** [comment]
https://github.com/tailwindlabs/prettier-plugin-tailwindcss this is also pretty nice

**Comment by Hy0tic** [comment]
> https://github.com/tailwindlabs/prettier-plugin-tailwindcss this is also pretty nice

added, gonna leave this as default setting for now

**Pull request merged**
